Makefile

Had an issue with a city failing to build due to OoM during the nominatim generation step.
This allows to override the resource limits, e.g.: `make DOCKER_MEMORY=16G JAVA_TOOL_OPTIONS=-Xmx16g Foo.up`

makefile: Add DOCKER_MEMORY,JAVA_TOOL_OPTIONS make params

---

geocoder/photon/Dockerfile
geocoder/photon/import_from_dump.sh

In order to use common base image. Note that tzdata is already installed in the new base image.
* upgrade openjdk from 8 to 11
* Add build args `PHOTON_VERSION` and `PHOTON_HASH`
* Strip version suffix from jar filename

photon: change base image to debian:bullseye-slim

---

docker-compose.yaml
web/Dockerfile
web/nginx.conf.template

This should make the image usable independently from the specific docker-compose setup in the repo.
- Allows overriding web container configuration via env vars:
-   `HEADWAY_PUBLIC_URL`
-  `HEADWAY_HTTP_PORT`
-    `HEADWAY_RESOLVER`
-   `HEADWAY_GRAPHHOPPER_URL`
-  `HEADWAY_NOMINATIM_URL`
- `HEADWAY_PHOTON_URL`
- `HEADWAY_TILESERVER_URL`
- Adds `build` directive to `docker-compose.yaml` to facilitate building images via `docker-compose build`
Note I had to add suffixes [`/data`](https://github.com/ellenhp/headway/compare/main...3nprob:web-env-config?expand=1#diff-af6bd4d7c8c60522ef8b9f2dfb92eb0e2a179dc172e33e527ced4996a8291a2eR48) and `/fonts` to get the requests route properly to the upstream containers - doesn't seem to be related to the templating change though.

Web env config

---

Makefile

* Build images now have common tag of `headway_build_mbtiles_$AREA_NAME` to indicate that they are contain area-specific data
* Remove these images when running `make clean_all`
* Remove leftover `tileserver_image`

Make clean build images

---

Makefile

Resolves #27 .
The difference with the previous implementation is that removing by tag rather than ID causes images to be untagged rather than error.

makefile: remove build images on clean_all

---

docker-compose.yaml

This should be safe to merge, and necessary for serving the bounding box I believe.

Add volume mount back to the nginx docker compose entry

---

mbtiles_build/Dockerfile
tileserver/image/Dockerfile

Self-explanatory. This bit me when I did a docker system prune and rebuilt.

Never use cached apt-get update for apt-get install

---

Earthfile
docker-compose.yaml
k8s/deployment-config-example.yaml
k8s/tileserver-deployment.yaml
services/tileserver/config.json.template
services/tileserver/init.sh
services/tileserver/style/style.json.template

I want to track OSM Liberty upstream a bit more closely but I did remove the 3d buildings again after copying over the style. I don't like 3d buildings for some reason.

Add self-hosted natural earth tiles and revert some changes to OSM Liberty

---

web/frontend/src/components/SearchBox.vue

Fixes #152 
Since we issue a lot of requests as we type-ahead, it's easy for them to complete out-of-order.
https://user-images.githubusercontent.com/217057/190509023-80b9af6b-f8f8-48a3-aef0-eaa6cf7e55de.mp4

Don't clobber autocomplete with older request

---

web/frontend/src/components/BaseMap.vue
web/frontend/src/components/SearchBox.vue
web/frontend/src/pages/PlacePage.vue
web/frontend/src/utils/models.ts

This is a followup to #153. Now that you can select localities, the zoom feature feels a little off.
**before**:
So now, when available, we prefer to use the bbox for fitting rather than the coordinate. This works much better for large POIs (e.g. "Seattle").
**after zooming to bbox (first commit)**:
So zooming in/out to Seattle looks good with the first commit, but zooming into Victrolla loses valuable context of the surrounding neighborhood. This is because, while many small venues are represented as OSM.Nodes, thus lacking a bbox, some (like Vitctrolla) are actually stored as OSM.Ways and thus have a bbox. 
So the second commit introduces a maxZoom, ensuring that if we are zooming to a Bbox we never zoom too close.
**before second commit (too close to small osm ways)**
**after second …

Don't overzoom large (city-sized) POIs

---

web/frontend/package.json
web/frontend/src/components/SearchBox.vue

The chosen delay (200ms) is pretty arbitrary. It "feels" fast enough while cutting my requests about in half, but feel free to play with it.
FIXES https://github.com/headwaymaps/headway/issues/118 (at least the parts of it that we want to do for now)

throttle pelias autocomplete

---

web/frontend/src/components/BaseMap.vue
web/frontend/src/utils/Prefs.test.ts
web/frontend/src/utils/Prefs.ts

Fixes #167 
To do this, we store previous map center and zoom in localStorage.
There's some special care taken to not store/fetch too often. Maybe this
is overkill with the debounce, but it seemed wasteful to potentially
trigger i/o as the user pans around or zooms in.
We also recall the users previous zoom - we wouldn't want to zoom in
*further* then they were previously zoomed. That could be particularly
disorienting if the user was at a global scale looking at an ocean or
something.
TBH this risk still exists if the user accidentally zooms way into an
ocean before closing their browser. It'd be nice to have some kind of
magic "is user staring at the ocean" check to short circuit this
behavior, but I _think_, even without that, the risk is worth trying out
the new UI.
Demo: …

Start zoomed on last location when possible.

---

web/frontend/src/pages/PlacePage.vue

FIXES: #166
I left my individual commits in case you want to follow the commit log narrative, but feel free to squash as you see fit:
- refactor: avoid unnecessary round trip
- update path on subsequent reloads
- clearer code
- restore error handling if given invalid osm_id

FIX: url doesn't update for subsequent searches

---

web/frontend/src/css/app.scss

This margin on the last item was undesirable anyway.
**before**
**after**

[www] Fit travel mode buttons on 1 row for iphone6/7/8

---

Earthfile
bin/publish-data
docker-compose-with-transit.yaml
docker-compose.yaml
k8s/_template/deployment-config.yaml.tpl
k8s/los-angeles-latest-hw-dev/deployment-config.yaml
k8s/planet-with-admin-v1.20-hw-0.1.0/deployment-config.yaml
k8s/planet-with-admin-v1.20-hw-dev/deployment-config.yaml
k8s/seattle-latest-hw-dev/deployment-config.yaml
services/otp/init.sh
services/pelias/init_elastic.sh
services/pelias/init_placeholder.sh
services/valhalla/init.sh

- Decreases decompression speed by about 10x (big yay!)
- Increases file size by about 0.3x (small boo!)
It also substantially increases compression speed, but I don't care so much about that as it only happens once when building assets, not on every deploy.
For me, and I expect many, decompression speed is the bottleneck, not
bandwidth. If you are on a slow network or have a very fast machine,
it's possible that decompression speed isn't your bottleneck and that
this change could be a little worse for you.
For everyone else (like me), you could expect up to about a 7x increase
in artifact deployment speed, less if your network gets saturated.
<details>
<summary>
Speed:
</summary>
```
++ xz -k input/Seattle.elasticsearch.tar --stdout
real    1m56.604s
user    1m56.380s
sys     0m0.220s
++ …
```

faster deploys with zstd

---

web/frontend/src/components/MultiModalListItem.vue
web/frontend/src/components/RouteListItem.vue
web/frontend/src/components/TransitSteps.vue
web/frontend/src/css/quasar.variables.scss
web/frontend/src/models/Itinerary.ts
web/frontend/src/services/OTPClient.ts
web/frontend/src/utils/format.ts

For transit travel, the "details" button now shows a timeline with all the legs
of the trip, with some details about that leg.
You can click on the transfer points in the timeline to get a closer look on
the map.
There are lots of improvements that could be made, but this seemed good enough
to be useful.
https://user-images.githubusercontent.com/217057/206323120-5494b04b-3115-4cd6-a580-233e2074ad77.mp4
Note that I've removed the "water fall" transit view for now. I think that, with some work, that waterfall UI could be useful to compare a bunch of options at once, so I'd like to bring it back one day, but for now I think this improvement is more straightforward and likely to be useful in the short term. I hope to bring it back one day.

transit timeline

---

web/frontend/src/components/BaseMap.vue
web/frontend/src/components/MultiModalListItem.vue
web/frontend/src/components/MultiModalSteps.vue
web/frontend/src/components/SingleModeListItem.vue
web/frontend/src/components/SingleModeSteps.vue
web/frontend/src/components/TransitSteps.vue
web/frontend/src/components/TripListItem.vue
web/frontend/src/css/app.scss
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/pages/StepsPage.vue

**before (single mode)**
Previously (and unchanged in this PR), the "details" button for single-mode would take you to a "steps" page.
**before (multimodal)**
But for multimodal, it would render the transit timeline in-line on the Alternates page. There wasn't much room to show you the various steps without scrolling a bunch.
**after (multimodal)**
Now the details button takes you to the "steps"  page for multimodal too, and I've increased the max-height available to the bottom card on that screen.
**after (single mode)**
Overall I think it's a small improvement, but I think there's some other easier things that can now be done to improve the steps screen, like...
- show the trip overview (from/to/duration)
- click on individual steps for the Routes (valhalla) to zoom to that step. We …

More room for steps (and move transit steps to "steps" page, like with other modes)

---

web/frontend/src/i18n/en-US/index.ts
web/frontend/src/models/Itinerary.ts
web/frontend/src/models/Route.ts
web/frontend/src/models/Trip.ts
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/pages/StepsPage.vue
web/frontend/src/router/routes.ts
web/frontend/src/services/OTPClient.ts
web/frontend/src/services/ValhallaClient.ts
web/frontend/src/utils/Result.ts

Previously, when routing to unsupported locations, we just silently failed. 
Now we try to show some helpful error text
When searching for transit directions fails, we'll try to suggest the user try another mode:

Show useful error when trying to route to an unsupported area

---

web/frontend/src/i18n/en-US/index.ts
web/frontend/src/models/Itinerary.ts
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/services/OTPClient.ts

If someone is trying to use transit directions without setting up an OTP instance, we now show a  (hopefully) useful error message.

handle disabled transit

---

web/frontend/src/components/SearchBox.vue
web/frontend/src/layouts/MainLayout.vue
web/frontend/src/pages/AlternatesPage.vue

This broke in #211. That's what I get for only testing on Safari's "responsive design mode" vs. an actual iOS device.
This isn't a complete fix, for instance, there's some unutilized screen real estate on iPhoneX style devices, but this should make things usable.

Fix: bottom UI obscured by navbar on iOS

---

web/frontend/src/components/BaseMap.vue
web/frontend/src/models/TripLayerId.ts
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/pages/PlacePage.vue
web/frontend/src/pages/StepsPage.vue
web/frontend/src/router/routes.ts

If the routes already drawn, just leave it, don't remove it only to redraw it. This can avoid a little flicker.
As part of this I centralized the code that generates layer ids.

Don't unnecessarily redraw the route when viewing steps

---

web/frontend/src/components/TripSearch.vue

Note to reproduce the previous buggy behavior, you have to click far away from a nameable address - e.g. click in the middle of nowhere.

[www] FIX blank search field for dropped pin

---

services/tileserver/configure_run.sh
services/tileserver/styles/basic/style.json

This is a fixup to 8d15b19
Previously we were templating the style file, but that's no longer necessarily. However, because it was a template, there were some escaped characters (${ESC} -> $). I failed to remove those in 8d15b19, which resulted in some roads (and presumably other features) not being styled properly.

[build] fix some roads not visible

---

web/frontend/src/components/BaseMap.vue
web/frontend/src/models/Itinerary.ts
web/frontend/src/models/Place.ts
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/pages/StepsPage.vue
web/frontend/src/utils/Prefs.test.ts
web/frontend/src/utils/Prefs.ts

Primarily: Fix some distances in non-preferred units.
(But in the process of debugging, I fixed up some other things, each in mostly tidy commits.)
In particular "use current location" doesn't do a geocoding request, which is when we'd get the country-code used to guess the preferred units.
Now we try two more things before falling back to the default unit (km):
1. fall back to the "to" location if the "from" location lacks a country code.
2. if both to/from lack units, fall back to whatever the previously used units were.
To reproduce the previous bug:
1. Search for "Fremont Troll"
2. Click "Transit" directions
3. Be somewhere in Seattle and click from "my location"
4. See "0.5 km of walking" but expect to see "0.3 _mi_ of walking"

[www] Fix some distances shown in non-preferred units.

---

.github/workflows/push-latest-containers.yml
Earthfile
bin/_headway_version.sh
k8s/bin/generate
k8s/configs/planet/frontend-deployment.yaml
k8s/configs/planet/opentripplanner-losangeles-deployment.yaml
k8s/configs/planet/opentripplanner-seattle-deployment.yaml
k8s/configs/planet/pelias-api-deployment.yaml
k8s/configs/planet/pelias-elasticsearch-deployment.yaml
k8s/configs/planet/pelias-placeholder-deployment.yaml
k8s/configs/planet/tileserver-deployment.yaml
k8s/configs/planet/transitmux-deployment.yaml
k8s/configs/planet/valhalla-deployment.yaml

This should hopefully make it a little easier to manage updates and the occasional rollback.

Only build the `latest` containers when a new tag is pushed. 

---

web/frontend/src/models/Itinerary.ts
web/frontend/src/models/Route.ts
web/frontend/src/models/Trip.ts
web/frontend/src/services/OTPClient.ts
web/frontend/src/services/ValhallaClient.ts

Some transit routes are associated with a color. We now color the active transit route according to this color when OTP makes this available.
(Thanks to @spammads for making me aware of this api!)

[www] color transit routes, unify line styles

---

web/frontend/.vscode/settings.json
web/frontend/src/components/BaseMap.vue
web/frontend/src/components/SearchBox.vue
web/frontend/src/components/SearchListItem.vue
web/frontend/src/components/TripListItem.vue
web/frontend/src/components/TripSearch.vue
web/frontend/src/css/app.scss
web/frontend/src/models/Place.ts
web/frontend/src/pages/AlternatesPage.vue
web/frontend/src/pages/BaseMapPage.vue
web/frontend/src/pages/PlacePage.vue
web/frontend/src/pages/SearchPage.vue
web/frontend/src/pages/StepsPage.vue
web/frontend/src/router/routes.ts
web/frontend/src/services/PeliasClient.ts
web/frontend/src/utils/Markers.ts
web/frontend/src/utils/misc.ts

You can now press enter to see all the search results rendered on the map at once.
https://user-images.githubusercontent.com/217057/216727334-ee015e81-d2da-4a77-ba2d-4115b078d126.mp4
There's plenty more to do to improve this (like pagination to "see more" more results!).
There were a couple of diversions while implementing this though, and I figure this is strictly better than what was there before, so I'm going to merge it without the following:
1. I initially assumed I'd want to use Pelias's "search" endpoint rather than the "autocomplete" endpoint, but I'm not convinced. The results are pretty different in some cases, and it's pretty strange to see a completely different set of results after hitting enter vs. what you were seeing in the autocomplete. See …

introduce search page

---

web/frontend/src/pages/AlternatesPage.vue

Previously there was no indication that the alternates on the screen were stale.
**before**
https://user-images.githubusercontent.com/217057/217965202-8cffb18b-badd-4e0a-813c-41949dda17a8.mp4
**after**
Now:
1. show an indicator whenever we're loading trips
2. clear results immediately once the inputs change
https://user-images.githubusercontent.com/217057/217965208-701c8711-1282-41a4-87a3-45b6fccd6697.mp4

[www] show indicator when loading alternates

---

k8s/_template/opentripplanner-AREA-deployment.yaml.tpl
k8s/configs/planet-dev/opentripplanner-losangeles-deployment.yaml
k8s/configs/planet-dev/opentripplanner-seattle-deployment.yaml
k8s/configs/planet/opentripplanner-losangeles-deployment.yaml
k8s/configs/planet/opentripplanner-seattle-deployment.yaml
k8s/configs/seattle-dev/opentripplanner-seattle-deployment.yaml

Java heap should be allowed to more or less fill the container limits.

[k8s] speed up larger OTP zones

---

.github/workflows/push-dev-containers.yml
.github/workflows/push-latest-containers.yml
services/frontend/nginx.conf.template

For our SPA to work, we route all requests for which a file can't be found, to index.html - assuming it's a page request that the js app router will handle.
But when the user loads from cache a stale index.html (from a previous deploy), we'll request assets, which include a stale cache-buster (like style.ab123.css). These should 404, but instead are hitting the fallback rule and are served the content of index.html - which results in a weird content-type error (expecting javascript, but receiving html).
So we now have a special rule for css/js assets - preventing them from being served the SPA app. 
We also mark assets for aggressive caching since they are immutable and set a pretty conservative cache for everything else.

avoid confusing error when serving stale assets

---

services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/components/SearchBox.vue
services/frontend/www-app/src/ui/ScaleControl.ts
services/frontend/www-app/src/ui/WrapperControl.ts
services/frontend/www-app/src/utils/Prefs.ts

https://user-images.githubusercontent.com/217057/224865377-336aa39b-ba12-4af3-a191-29aaba50e03d.mp4
There wasn't quite enough room for the attribution and the map scale on some mobile devices, so on mobile, I've bumped the scale up to the same line as the "geolocate" button.
You can tap the map scale to swap units, and it'll remember it for next time. 
I'm a little worried that on mobile this tap target will be too close to the geolocate button, but let's try it out.
Speaking of worries, I'm not sure about the debounce. The delay between zooming and seeing the scale update feels strange, but I felt a shorter delay still felt choppy. At least now it feels a little more explicable - you finish panning/zooming and *then* it updates. Having *no* debounce at all is an option, but it seems like …

[www] add map scale

---

services/frontend/www-app/src/components/SearchBox.vue
services/frontend/www-app/src/components/TripSearch.vue
services/frontend/www-app/src/layouts/MainLayout.vue
services/frontend/www-app/src/pages/BaseMapPage.vue

This is a followup to https://github.com/headwaymaps/headway/pull/243, in which I initially tried (and failed) to overhaul the search widget. The details of the previous failure are in the reverted commit:
https://github.com/headwaymaps/headway/commit/7f0f396da39ee775b78bc8b436f75ce7c88b0a3e
The improvements here are:
- UX: You can choose items from the autocomplete with your  keyboard arrows and Enter
- Design polish: The width of autocomplete menu matches search field
- Design polish: Removes the rounded corners between the input and menu, forming a nice continuous widget.
- UX: better tab indexing
https://user-images.githubusercontent.com/217057/225184207-46a865bb-650a-4807-9e27-d677b1a61353.mp4
- note the rounded corners between the menu and input
- note the mismatched widths between …

improve search bar layout and add keyboard navigation

---

services/frontend/www-app/src/components/SearchBox.vue

Note that this was an issue even before the big search bar refactor in 2ca6fbb

[www] FIX: autocomplete menu shows stale results after swap locations

---

Earthfile
bin/build-los-angeles
bin/build-planet
bin/build-transit
bin/publish-data
k8s/configs/planet-dev/deployment-config.yaml
k8s/configs/planet/deployment-config.yaml
k8s/planet.env

This PR consists of a few tiny changes and then two slightly larger ones:
Transit graphs are built from GTFS feeds, which have a specific finite calendar. Since they expire, it's helpful to label them with their creation date to get some kind of idea of which ones are more relevant.
Headway requires an OSM extract to produce it's tiles, transit routing, non-transit routing, geocoding, etc.
There's two ways to get this extract: You can bring your own `<filename>.osm.pbf`, and specify `--area=<filename>` **or** you can specify an `--area=Cityname` with a  Cityname that corresponds to one of the bbbike.org extracts, which will be downloaded at build time.
If you were bringing your own data, and the area you were using to build your transit zone didn't match the area of your …

transit: datestamp graphs and build them from the same basemap data

---

services/tileserver/styles/basic/style.json

Previously we were rendering the labels, but not the route lines.
**before**
**after**

[tileserver] render ferry route lines

---

services/tileserver/styles/basic/style.json

See https://maps.earth/place/-124.2153059153271,47.24507569180591
The Moclips River dumps into the Pacific Ocean, but with the previous rendering it appears like there is a bunch of sand between where the river ends and the ocean begins.
Some related discussion:
https://help.openstreetmap.org/questions/49790/coastline-at-highwater-vs-lowwater
> It has been a long-held practice in OSM (2008 or earlier) to map
coastlines at the Mean High Water Spring as stated here:
The new layer ordering seems to be more consistent with how the map is expected to be rendered, though regional norms might vary.
**before**
**after**
In this area, it means we end up not showing any sand, because it's under the high tide line where the water is mapped. It might be nice if we could include some kind of tidal …

[tileserver] water above sand, waterways above water

---

services/frontend/www-app/src/models/Itinerary.ts

Added the other missing icons as well.
**before**
note the weird _undefined_ text in the route summary
**after**

[www] Fix: ferry icon missing in transit directions

---

services/transitmux/src/bin/transitmux-server/plan.rs

URL encoded query strings will fail to deserialize as borrowed strings.
This doesn't affect the current deployment, but I'm working on another feature that ran into this.

[transitmux] accept URL encoded query params

---

services/frontend/www-app/src/components/TripSearch.vue
services/frontend/www-app/src/i18n/en-US/index.ts
services/frontend/www-app/src/models/Itinerary.ts
services/frontend/www-app/src/models/Trip.ts
services/frontend/www-app/src/pages/AlternatesPage.vue
services/frontend/www-app/src/pages/StepsPage.vue
services/frontend/www-app/src/services/OTPClient.ts

Previously transit routing always assumed you wanted to leave right now. Now you can specify the time and date you'd like to depart.
https://user-images.githubusercontent.com/217057/227674057-b848a34e-80ce-467b-81de-c47a962f4c90.mp4
Notes:
- Follow up work would be to add an "arrive by" feature which OTP also supports.
- I'm using the browser native time/date fields because they were expedient. They feel efficient for keyboard users, but might not be very intuitive. We can revisit.
- This should probably be debounced/throttled.

Set "Depart at" for transit

---

services/frontend/www-app/src/components/PlaceCard.vue
services/frontend/www-app/src/components/PlaceField.vue
services/frontend/www-app/src/models/Place.ts

This is some progress on #178 - starting with just the web and phone info.
I'm starting there because it's easy - it's already part of our pelias response. 
I'm going to follow up with some rudimentary edit support - I think, for now anyway, this is going to look like "link back to OSM to edit", but I want to do a little more research about the best way to communicate that, especially for people who aren't familiar with OSM.
**before**

Place card shows website and phone number when available

---

.github/workflows/checks.yml
.github/workflows/push-dev-containers.yml
.github/workflows/push-latest-containers.yml
services/frontend/www-app/package.json
services/frontend/www-app/src/boot/i18n.ts
services/frontend/www-app/src/components/OpeningHoursStatus.vue
services/frontend/www-app/src/components/OpeningHoursTable.vue
services/frontend/www-app/src/components/PlaceCard.vue
services/frontend/www-app/src/components/PlaceField.vue
services/frontend/www-app/src/i18n/en-US/index.ts
services/frontend/www-app/src/models/OpeningHours.test.ts
services/frontend/www-app/src/models/OpeningHours.ts
services/frontend/www-app/src/models/Place.ts
services/frontend/www-app/src/utils/format.ts
services/frontend/www-app/yarn.lock

After you tap/click "show hours"
A more complicated one:
Note that the current "status" (whether it's "open until..." or "closed until..." ) assumes you're looking at places only within your own timezone, which is obviously flawed.
I think addressing that might be non-trivial. Maybe we could plumb the timezone of each place through pelias? As it is, I believe it's the common case that people are looking for hours in their own timezone, and thus useful enough to include, even with this limitation.

Expose OSM's opening hours

---

services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/components/MultiModalSteps.vue
services/frontend/www-app/src/components/PlaceCard.vue
services/frontend/www-app/src/components/SearchListItem.vue
services/frontend/www-app/src/components/SingleModeSteps.vue
services/frontend/www-app/src/layouts/MainLayout.vue
services/frontend/www-app/src/pages/BaseMapPage.vue
services/frontend/www-app/src/pages/SearchPage.vue
services/frontend/www-app/src/pages/StepsPage.vue

This change affects the search page, e.g. https://maps.earth/search/coffee
**before**
Previously, only name and address were surfaced. 
**After**
Now we show open hours and the other POI information we have in a separate card.  On desktop this card floats, on mobile the card replaces the search results, but you can quickly go "back" to the search results to keep browsing.
Also:
- fixed an off-by-one error when the browser was the exact breakpoint width.
- you now zoom out when "deselecting" a search result.

Show place details as you click through search results

---

services/frontend/www-app/src/components/MultiModalListItem.vue
services/frontend/www-app/src/models/Itinerary.ts

- [www] Fix: transit timeline to faint in Chrome
- [www] arrows in transit timeline were too crowded
**before**
**after**

transit timeline design tweaks

---

services/frontend/www-app/quasar.config.js
services/frontend/www-app/src/components/BaseMap.vue

3d buildings are neat, but especially with very tall buildings they can obscure useful parts of the map.
Opacity is one way of dealing with this, but even with opacity, things get obscured and IMO they look noisier.
Another option would be to add a toggle to the screen to enable/disable the 3d effect, but I don't like the idea of taking up more screen real estate for yet another button. Better would be to do something by default that (most) people (mostly) like.
So I chose to only show the 3d buildings when zoomed in substantially, and I dampened the height of buildings to minimize how much they'd "bleed" into the map. My hope is that it's a subtle thing that enriches the map, helping to orient people, without being too distracting. …

[www] render 3-d buildings

---

services/frontend/www-app/src/components/BaseMap.vue
services/tileserver/styles/basic/style.json

Motivations:
- Buildings were a little too prominent
- 3-d buildings can be distracting, so only show them when zoomed in a bit further
- move the water color away from "pure blue" towards a more aquatic green/blue.
- push background away from pure gray, which maybe feels a bit less drab

[basemap] small tweaks to map style:  water, background, and building style

---

services/frontend/www-app/src/i18n/en-US/index.ts
services/frontend/www-app/src/pages/SearchPage.vue

Previously it wasn't really clear if the search completed.

"No search results" instead of blank text

---

services/frontend/www-app/src/components/BaseMap.vue

[basemap] fix jagged building rendering

---

.env-example
Earthfile
bin/publish-data
docker-compose-with-transit.yaml
docker-compose.yaml
k8s/_template/deployment-config.yaml.tpl
k8s/_template/tileserver-deployment.yaml.tpl
k8s/configs/planet-dev/deployment-config.yaml
k8s/configs/planet-dev/tileserver-deployment.yaml
k8s/configs/planet/deployment-config.yaml
k8s/configs/planet/tileserver-deployment.yaml
k8s/configs/seattle-dev/deployment-config.yaml
k8s/configs/seattle-dev/tileserver-deployment.yaml
services/tileserver/init.sh
services/tileserver/styles/basic/style.json
services/tileserver/templates/config.json.template

Otherwise the ground feels a bit sparse in many places, while less sparse in a few places that have good OSM coverage.
This allows for dynamic styling of landcover and keeps it visible at higher zoom levels.
**before**
**after**

Add vector landcover to terrain for low zoom

---

services/frontend/www-app/src/components/BaseMap.vue

According to OSM attribution guidelines:
> You may use a mechanism to fade/collapse the attribution [...] automatically after five seconds.
On mobile in particular, the attribution is a dangerous tap target on small screens. I keep hitting it while trying to geolocate.
We could keep shuffling it around, but there just isn't that much space for people with small mobile devices, so this helps.

Hide attribution control after a delay.

---

services/frontend/www-app/src/components/MultiModalListItem.vue
services/frontend/www-app/src/i18n/en-US/index.ts

*before* if a departure occurred in the past, you'd see
*now* you'll see something like:

[ui] Show "2 minutes ago" rather than "in -120 seconds"

---

services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/models/Itinerary.ts
services/frontend/www-app/src/models/Route.ts
services/frontend/www-app/src/models/Trip.ts
services/frontend/www-app/src/models/TripLayerId.ts
services/frontend/www-app/src/pages/AlternatesPage.vue
services/frontend/www-app/src/pages/StepsPage.vue
services/frontend/www-app/src/utils/Markers.ts

Otherwise it can be hard to see precisely where you switch buses or start walking.
The former is a bigger problem than the latter, but I think it's worth showing for pedestrian leg start/ends as well for design consistency with the transit timeline "nodes" (in the left panel/bottom card).
**before:**
**after:**
**annotated (in case you missed it 😉):**

[ui] mark transfers / legs

---

services/tileserver/styles/basic/style.json

admin_level=3&4 boundaries typically correspond to things at the scale of a state or province.
Previously we were only showing those boundaries when zoomed way in.
There is a bit of tension between large countries and small countries, but I've tried to apply some design treatments that strike the right balance. 
It might be nice to have some kind of per-country style rule, to opt the 7 or 8 largest countries into a special case, but we don't have an easy way to ask "what country is this province border in" in the style rules. Maybe some kind of custom planetiler build would accomplish that, but it was more work than I was ready to prioritize at the moment.

show state borders sooner

---

services/frontend/www-app/src/components/PlaceCard.vue

Just a little css tweak
**before**
**after**

[ui] add missing padding to "edit on osm" link

---

services/frontend/www-app/src/layouts/MainLayout.vue

We weren't properly accounting for UI elements like the navbar which can
obscure the screen, requiring you to scroll down to see these elements.
**before**
**after**

[ui] android: keep geolocate and scale on screen

---

services/frontend/nginx.conf.template

I broke this in 1f567b7
From https://docs.nginx.com/nginx/admin-guide/web-server/web-server/
== NGINX Location Priority ==
1. Test the URI against all prefix strings.
2. The = (equals sign) modifier defines an exact match of the URI and a prefix string. If the exact match is found, the search stops.
3. If the ^~ (caret-tilde) modifier prepends the longest matching prefix string, the regular expressions are not checked.
4. Store the longest matching prefix string.
5. Test the URI against regular expressions.
6. Stop processing when the first matching regular expression is found and use the corresponding location.
7. If no regular expression matches, use the location corresponding to the stored prefix string.
==
The broken request: /tileserver/styles/basic/sprite@2x.png
Before 1f567b7, we …

[www] fix 404 on spritesheet

---

services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/ui/LocationControl.test.ts
services/frontend/www-app/src/ui/LocationControl.ts
services/frontend/www-app/src/utils/DeviceOrientationPolyfill.ts
services/frontend/www-app/src/utils/GeolocationPolyfill.ts
services/frontend/www-app/src/utils/env.ts

Some mobile browsers support reporting device orientation. On those
platforms we now show a visible compass direction whenever the
geolocation dot is shown to help orient the user.

[www] Show compass on supported platforms

---

services/frontend/www-app/.eslintrc.js
services/frontend/www-app/package.json
services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/ui/LocationControl.ts
services/frontend/www-app/src/utils/DeviceOrientationPolyfill.ts

Currently the device indication indicator is rendered assuming the map is always "north-on-top". If you rotate the map, the indicator will point in an inaccurate direction.

Fix: device orientation indicator should rotate with map

---

services/frontend/www-app/public/headway-dev-config.json
services/frontend/www-app/src/components/SearchBox.vue
services/frontend/www-app/src/pages/BaseMapPage.vue
services/frontend/www-app/src/utils/Config.ts

Configurable "About" and "Contact us" links

---

services/frontend/www-app/.eslintrc.js
services/frontend/www-app/src/components/BaseMap.vue
services/frontend/www-app/src/i18n/en-US/index.ts
services/frontend/www-app/src/ui/LocationControl.ts
services/frontend/www-app/src/utils/DeviceOrientationPolyfill.ts

By default, if you deny location services (or have perhaps long ago denied location services), maplibre will render the geolocate button as disabled. But it's not really enough information to tell you whats going on.
Now, if a user tries to geolocate, but cannot, we show a dismissible explanation alongside the disabled button.

minimize confusion when location services are denied

---

.github/workflows/checks.yml
Earthfile
bin/build
services/tilebuilder/percent-of-available-memory

Some really impressive file-size gains. I just need to test these new planet assets before merging.
```
115G    maps-earth-planet-v1.36/maps-earth-planet-v1.36.mbtiles
86G     maps-earth-planet-v1.40/maps-earth-planet-v1.40.mbtiles
```
Note that this is also comparing two different planet inputs, so it's not a great test, but the planet build process is so slow that I'm not willing to run a more precise experiment at the moment.

Planetiler update

---

services/travelmux/src/api/v2/plan.rs
services/travelmux/src/valhalla/valhalla_api.rs

Remember, travelmux now combines responses from Valhalla and OTP. 
Put the per-leg maneuver data into the coalesced "Travelmux" legs, currently it's only valhalla maneuvers in the legs, but more to follow soon!

[travelmux] maneuver data

---

services/travelmux/src/valhalla/valhalla_api.rs

Clicking on a route step and non-transit routing was not rendering.
I broke this while working on the travelmux API unification. I
unwittingly committed some code to the wrong file that made valhalla api
responses camelcase.
OTP is camelCase and Valhalla is snake_case. I decided to adopt
camelCase for the unified responses, but my intention was always to
leave the original _valhalla and _otp responses untouched so that legacy
clients could easily migrate.

[www] Fix valhalla routing instructions

---

bin/_headway_version.sh
docker-compose-with-transit.yaml
docker-compose.yaml
k8s/_template/pelias-elasticsearch-deployment.yaml.tpl
k8s/configs/planet-dev/deployment-config.yaml
k8s/configs/planet-dev/opentripplanner-barcelona-config.yaml
k8s/configs/planet-dev/opentripplanner-losangeles-config.yaml
k8s/configs/planet-dev/opentripplanner-pugetsound-config.yaml
k8s/configs/planet-dev/pelias-elasticsearch-deployment.yaml
k8s/configs/planet/deployment-config.yaml
k8s/configs/planet/opentripplanner-barcelona-config.yaml
k8s/configs/planet/opentripplanner-losangeles-config.yaml
k8s/configs/planet/opentripplanner-pugetsound-config.yaml
k8s/configs/planet/pelias-elasticsearch-deployment.yaml
k8s/configs/seattle-dev/pelias-elasticsearch-deployment.yaml
services/pelias/docker-compose-import.yaml

es8 support for pelias is experimental. I've done a test build and have been running it in production for a couple of days now seemingly without issue.
Note the pelias code still uses the legacy elasticsearch client. It just takes advantage of that fact that es8 is backwards compatible with the legacy client.
See https://github.com/pelias/pelias/issues/953 for more

Use es8 container with pelias

---

services/travelmux/src/api/v2/plan.rs
services/travelmux/src/api/v3/plan.rs
services/travelmux/src/valhalla/valhalla_api.rs

This field is usually populated - but apparently not always. Now it's properly marked as Optional.

[travelmux] `verbal_pre_transition_instruction` field is optional

---

services/travelmux/src/api/v4/plan.rs
services/travelmux/src/otp/otp_api.rs
services/travelmux/src/util.rs
services/travelmux/src/valhalla/valhalla_api.rs

This allows building a transit timeline without accessing the raw OTP response.

[travelmux] add start/end to each trip leg

---

services/frontend/www-app/public/.well-known/apple-app-site-association

Currently this is hardcoded to the maps.earth iOS app, but I'm happy to template this if someone cares and wants to do the leg work.
In the meanwhile, it won't have any affect for other domains unless the iOS app is updated to work with those domains.

Allow universal links for iOS native app

---

Earthfile
services/otp/dem-hgt-to-tif

Valhalla has a really nice tool for downloading elevation data by bbox. 
OTP can use this data to produce better bike/walk directions. 
Valhalla can also use this data, but the planet wide dataset is >1TB, so I'm not going to incorporate it yet. If someone would like to incorporate it for smaller areas via a flag, I'd be open to it.

[OTP] Import elevation for better walking and biking
