web/.dockerignore, web/Dockerfile
Reduces resulting image size from 1.39GB to 143MB.
=> web: two-stage build Dockerfile

BUILD.md, README.md
I can be very verbose when I don't need to be so I just wanted to make a second pass through some of this. I also updated the status because we've made some progress since anyone touched the readme.
=> Make the readme a bit less verbose, and fix BUILD.md formatting

Makefile, otp/run/Dockerfile
Brings the valhalla build in line with #21
=> makefile: refactor valhalla building

README.md, web/frontend/quasar.config.js, web/frontend/src/components/PlaceCard.vue, web/frontend/src/pages/DirectionsPage.vue
This also changes the dev server config to proxy to the demo server because my laptop can't run headway anymore (aarch64 joys)
=> Add driving and walking modes

README.md, web/frontend/src/components/PlaceCard.vue, web/frontend/src/css/app.scss, web/frontend/src/css/quasar.variables.scss, web/frontend/src/pages/DirectionsPage.vue, web/frontend/src/pages/MultimodalPage.vue, web/frontend/src/router/routes.ts, web/frontend/src/third_party/decodePath.ts
I don't have a frontend contributor right now to run this by so I think I'll just merge it. This PR also contains minor frontend cleanup and a README.md update.
=> Add frontend for multimodal routing

web/frontend/src/pages/BaseMapPage.vue, web/frontend/src/pages/DirectionsPage.vue, web/frontend/src/pages/DroppedPinPage.vue, web/frontend/src/pages/MultimodalPage.vue, web/frontend/src/pages/PlacePage.vue
=> Show destination marker in directions screen

BUILD.md, Makefile
Just what it sounds like. Nice work on this!
=> Reorder Makefile so it can be more easily read from top to bottom

README.md
Minor quality-of-life improvement for first-time visitors
=> Link directly to BUILD.md in the readme

Makefile
Tested make locally, and it works! Hard to figure out my version of `make` comes from, but I'm fairly sure it's XCode CLI tools, which would mean lots of mac users would have a similar issue. 
Make version:
```bash
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
```
Closes #54
=> Remove oneshell directive from makefile, swap to set -e pattern

web/nginx.conf.template
Also set sub_filter_last_modified on to preserve last modified header.
Quick fix for https://github.com/headwaymaps/headway/issues/59.
=> Added https subfilter to nginx.conf.template.

web/frontend/src/components/SearchBox.vue, web/frontend/src/components/models.ts, web/frontend/src/pages/PlacePage.vue
Fixes #41 
This also cleans up some duplicated logic.
=> Use 'type' field from nominatim response for display name

web/frontend/src/components/models.ts
Also removes some superfluous log statements.
=> Fix formatting of address in placecard & search bar

BUILD.md
Updates docs to fix #72 
Also add some clarification about what was meant by "local installations"
=> Add information to docs about GTFS config

.gitignore, Makefile, docker-compose.yaml, geocoder/nominatim/Dockerfile, geocoder/nominatim/restore_then_start.sh, geocoder/nominatim_build/Dockerfile, geocoder/nominatim_build/import_then_dump.sh, geocoder/photon/Dockerfile, geocoder/photon/untar_and_start.sh, geocoder/photon_build/Dockerfile, geocoder/photon_build/import_from_dump.sh, valhalla/build/Dockerfile, valhalla/run/gen_hash.sh
This just makes things a bit more uniform which is nice. It also shrinks the nominatim.sql artifacts dramatically.
=> Compress processed data and use pbzip2 for (de)compression

BUILD.md, Makefile, docker-compose.yaml, web/init.sh
=> Support arbitrary OSM extracts

.github/workflows/main.yml
This will be really cool if it works!
=> Add basic CI that builds data for Adelaide

.github/workflows/main.yml, README.md
Also changes the order of some of the badges.
=> Add build status to README.md

.github/workflows/push.yml, Earthfile
I have no idea if this will work but I think it will. If anyone knows how to test CI pipelines effectively without pushing to main let me know :)
=> Push images on merge to main

.github/workflows/push.yml, docker-compose-no-interp.yaml, docker-compose.yaml
This also updates the docker-compose file to pull from docker hub.
=> Fix a few issues with the push CI job

.github/workflows/push-dev.yml, .gitignore, Earthfile, docker-compose.yaml, k8s/deployment-config-example.yaml, k8s/elasticsearch-deployment.yaml, k8s/elasticsearch-service.yaml, k8s/headway-deployment.yaml, k8s/headway-service.yaml, k8s/libpostal-deployment.yaml, k8s/libpostal-service.yaml, k8s/opentripplanner-deployment.yaml, k8s/opentripplanner-service.yaml, k8s/pelias-api-deployment.yaml, k8s/pelias-api-service.yaml, k8s/placeholder-deployment.yaml, k8s/placeholder-service.yaml, k8s/tileserver-deployment.yaml, k8s/tileserver-service.yaml, k8s/valhalla-deployment.yaml, k8s/valhalla-service.yaml, services/pelias/docker-compose-import.yaml, services/pelias/init_config.sh, services/pelias/init_elastic.sh, services/pelias/init_placeholder.sh, services/pelias/pelias.json.template, services/pelias/wait.sh, services/valhalla/init.sh, web/nginx.conf.template
=> Add Kubernetes configs for planet-scale instance

k8s/elasticsearch-deployment.yaml
This should help it handle a bit more traffic hopefully? Also bumping replica count down.
=> Update ES heap size

web/frontend/package.json, web/frontend/src/components/SearchBox.vue, web/frontend/src/components/models.ts, web/frontend/yarn.lock
=> Fix localizeAddress (actually localizes now!)

web/frontend/src/components/BaseMap.vue
=> Make long-press work on mobile

web/frontend/src/components/BaseMap.vue
=> Add compass control

web/frontend/src/components/BaseMap.vue, web/frontend/src/components/models.ts, web/frontend/src/pages/BaseMapPage.vue, web/frontend/src/third_party/decodePath.ts
There's currently a lot of latency during this operation but it does work. In the future we should put a service in front of Pelias to calls to the place endpoint by lat/lng and name using the reverse geocode endpoint+place endpoint. 
Fixes #120
=> Allow selection of POIs

Earthfile
=> Don't let wget spam during earthly builds

web/frontend/src/components/BaseMap.vue, web/frontend/src/components/models.ts, web/frontend/src/pages/BaseMapPage.vue
There are lots left but this is a good start on the journey to type-safety. Lots of frontend work remaining so it makes sense to spend time on this :)
=> Remove the need for some of the eslint disable directives

web/frontend/README.md, web/frontend/package.json, web/frontend/quasar.config.js, web/frontend/src/boot/i18n.ts, web/frontend/src/components/SearchBox.vue, web/frontend/src/i18n/en-US/index.ts, web/frontend/src/i18n/es/index.ts, web/frontend/src/i18n/index.ts
First part of fix for https://github.com/headwaymaps/headway/issues/127, importing the necessary packages and one POC translation.
=> Import I18n packages for #127

README.md
=> Clarify the cities and areas supported

BUILD.md, FULL_PLANET.md, README.md
This simplifies the readme.
Closes #141
=> Add basic full-planet documentation

web/frontend/src/boot/i18n.ts, web/frontend/src/i18n/en-US/index.ts, web/frontend/src/i18n/lang.ts, web/frontend/src/pages/AlternatesPage.vue, web/frontend/src/pages/DroppedPinPage.vue, web/frontend/yarn.lock
=> i18n for 2 .vue files

web/frontend/src/components/BaseMap.vue
(This is my first PR here - thanks for the project, and let me know if I've messed anything up!)
The permissions api isn't available until Safari 16, which was only released a couple days ago. This causes `flyTo` and `fitBounds` not to work on Safari pre-16.
So, eventually this could probably go away, but in the meanwhile I think it'd be good to fix.
=> Fix flyTo and geolocate button on Safari 15

VALUES.md
I've been meaning to write these down. They make sense to me.
=> Add Headway's values to the repo

Earthfile, docker-compose.yaml, services/pelias/docker-compose-import.yaml, services/pelias/pelias.json.template
Fixes #153 
This also includes some formatting fixes.
=> Import WOF data into elasticsearch

git-hooks/pre-commit
Fixes #126  (If I understood correctly)
=> Add pre-commit hook

.github/workflows/frontend-checks.yml, web/frontend/package.json, web/frontend/yarn.lock
=> Frontend: fix tests and run them in CI

web/frontend/src/components/BaseMap.vue, web/frontend/src/components/TripSearch.vue, web/frontend/src/pages/AlternatesPage.vue, web/frontend/src/pages/BaseMapPage.vue, web/frontend/src/pages/MultimodalPage.vue
**before:**
**after:**
**in action:**
https://user-images.githubusercontent.com/217057/203432888-be82d5dd-e4bf-4106-b48b-37e15f08b359.mp4
=> new button swaps to/from locations (and some fixups to the search bars)

web/frontend/src/components/BaseMap.vue
https://user-images.githubusercontent.com/217057/205412095-6041c780-32cc-4b5c-88d7-221a05cbe3a1.mp4
video showing:
1. the hover behavior
2. clicking on a POI we successfully reverse geocode
3. clicking on a POI we fail to reverse geocode, so show a pin instead
=> Clickable cursor for POIs and better fallback when a click's reverse geocoding fails.

Earthfile
Dropped a commit between testing and merging #190 🤦
=> fixup! [deploy] faster deploys with zstd

BUILD.md
Closes https://github.com/headwaymaps/headway/issues/195
=> Clarify countries argument in BUILD.md

web/frontend/src/components/SingleModeSteps.vue
Similar to what we have for multimodal routes, clicking on an individual step will now zoom the map to where that turn occurs.
https://user-images.githubusercontent.com/217057/207146970-8e355117-2238-4d01-b9e4-36fffe8fde6a.mp4
=> [www] click to zoom to step for valhalla routes.

web/frontend/src/pages/AlternatesPage.vue, web/frontend/src/pages/StepsPage.vue
Previously we were only showing markers when both to/from were set, now we'll show either. Importantly, these means when navigating from the Place page to the Alternates page we'll leave the marker on the map.
=> [www] show markers whenever possible, fit route

.github/workflows/push-latest-containers.yml, BUILD.md, Earthfile
This is a grab bag of small things I've improved while working on a different feature. I pulled them out into this PR to make the other branch more focused.
Changes are described in the individual commits.
=> little fixes

Earthfile, bin/build-seattle, services/gtfs/enumerate_gtfs_feeds.py
I also refactored the services/gtfs/enumerate_gtfs_feeds.py to take the file as an input argument, rather than downloading it inline.
=> [build] cache mobilitydb transit feeds file

.github/workflows/checks.yml, services/pelias/cities_to_countries.csv
Fixes https://github.com/headwaymaps/headway/issues/147
And secondarily:
- removed default args
- exercised the "guessed country" path
- no reason to log in to docker
=> [ci] speed up CI (hopefully)

Earthfile, bin/build-seattle, bin/publish-data, bin/publish-images, docker-compose-with-transit.yaml, k8s/_template/opentripplanner-AREA-deployment.yaml.tpl, k8s/_template/pelias-libpostal-deployment.yaml.tpl, k8s/_template/valhalla-deployment.yaml.tpl, k8s/maps-earth-planet-v1.21-0.3.0-containers-0.2.0-schema/opentripplanner-losangeles-deployment.yaml, k8s/maps-earth-planet-v1.21-0.3.0-containers-0.2.0-schema/opentripplanner-seattle-deployment.yaml, k8s/maps-earth-planet-v1.21-0.3.0-containers-0.2.0-schema/pelias-libpostal-deployment.yaml, k8s/maps-earth-planet-v1.21-0.3.0-containers-0.2.0-schema/valhalla-deployment.yaml, k8s/maps-earth-planet-v1.21-dev-containers-0.2.0-schema/opentripplanner-losangeles-deployment.yaml, k8s/maps-earth-planet-v1.21-dev-containers-0.2.0-schema/opentripplanner-seattle-deployment.yaml, k8s/maps-earth-planet-v1.21-dev-containers-0.2.0-schema/pelias-libpostal-deployment.yaml, k8s/maps-earth-planet-v1.21-dev-containers-0.2.0-schema/valhalla-deployment.yaml, k8s/seattle-latest-dev-containers-dev-schema/opentripplanner-seattle-deployment.yaml, k8s/seattle-latest-dev-containers-dev-schema/pelias-libpostal-deployment.yaml, k8s/seattle-latest-dev-containers-dev-schema/valhalla-deployment.yaml
edit: I also included some admin/deploy changes that come up while testing this. 
The individual commits are pretty tidy, so I'm including them in this PR.
=> Update Valhalla and OTP

web/frontend/src/components/BaseMap.vue, web/frontend/src/pages/AlternatesPage.vue
You can now click on one of the alternate routes to select it.
https://user-images.githubusercontent.com/217057/213305456-d2328d74-67c7-40e5-b0c3-9b4725f97c5f.mp4
=> [www] click on alternate route to select

web/frontend/src/components/BaseMap.vue, web/frontend/src/components/TripSearch.vue, web/frontend/src/utils/GeolocationPolyfill.ts, web/frontend/src/utils/env.ts
(supersedes #231)
Primarily: Geolocation now updates as you walk around, and some commits to deal with the fallout.
This also shows a better UI when location access is denied/disabled
=> Geolocation UI improvements

web/frontend/src/components/BaseMap.vue
Introduced in b2eeeef
Broken in 6d655f2
=> [www] fix showing pointer even after leaving POI

web/frontend/src/components/MultiModalSteps.vue, web/frontend/src/models/Itinerary.ts, web/frontend/src/services/OTPClient.ts
Fixes #237 (I think)
I missed a few modes because my city doesn't have a subway. 😅
=> [www] Add missing mode icons

Earthfile, bin/build-los-angeles, docker-compose-with-transit.yaml, docker-compose.yaml
Bundling these together because they aren't very exciting - comments are in the individual commit messages.
=> grab-bag of build tweaks

services/frontend/www-app/src/components/PlaceCard.vue, services/frontend/www-app/src/components/SearchBox.vue, services/frontend/www-app/src/i18n/utils.ts, services/frontend/www-app/src/models/Place.ts, services/frontend/www-app/src/pages/PlacePage.vue, services/frontend/www-app/src/utils/format.ts
Also included is some related cleanup.
=> Use Lat/Lon in search box for unnamed places

services/frontend/www-app/src/pages/AlternatesPage.vue, services/frontend/www-app/src/pages/SearchPage.vue
Same as #245, but on the /search page.
Also, we now handle errored requests.
=> loading indicator on search page

services/frontend/www-app/src/layouts/MainLayout.vue, services/frontend/www-app/src/pages/BaseMapPage.vue
Also, I extracted the sizing logic into css vars+calc. I think it's a bit more comprehensible now.
=> [www] max width for left panel

services/frontend/www-app/src/components/SearchBox.vue
I fixed a similar bug in 9c9d4aebf3eef56f48007be2a0b3dbf7c86b7d4c, but I reintroduced it at some point - I think maybe in my first failed attempt at overhauling the search widget in 14369e99e07c3047b7adeb130c0cca1bde771c43.
=> [www] fix stale autocomplete results (again)

Earthfile, bin/_headway_version.sh, builds/planet/env.sh, k8s/configs/planet-dev/deployment-config.yaml, k8s/configs/planet-dev/opentripplanner-losangeles-config.yaml, k8s/configs/planet-dev/opentripplanner-pugetsound-config.yaml, k8s/configs/planet/deployment-config.yaml, k8s/configs/planet/opentripplanner-losangeles-config.yaml, k8s/configs/planet/opentripplanner-pugetsound-config.yaml, services/frontend/www-app/package.json, services/frontend/www-app/quasar.config.js, services/frontend/www-app/yarn.lock
An omnibus of updating upstream dependencies.
Note that because we're updating Valhalla and OTP, their artifacts will need to
be rebuilt before deploying.
=> dependency updates

Earthfile, docker-compose-with-transit.yaml
- Remove unused configuration
- remove unused args
- supress unnecessary stdout
=> little cleanups

Earthfile, FULL_PLANET.md, bin/build, bin/build-transit, bin/most-recent.sh, builds/planet/env.sh, k8s/configs/planet-dev/deployment-config.yaml, k8s/configs/planet-dev/opentripplanner-barcelona-config.yaml, k8s/configs/planet-dev/opentripplanner-losangeles-config.yaml, k8s/configs/planet-dev/opentripplanner-pugetsound-config.yaml, k8s/configs/planet/deployment-config.yaml, k8s/configs/planet/opentripplanner-barcelona-config.yaml, k8s/configs/planet/opentripplanner-losangeles-config.yaml, k8s/configs/planet/opentripplanner-pugetsound-config.yaml, services/pelias/init_elastic.sh
Mostly this is about optimizing speed and size of builds by removing intermediate layers from our builds where possible.
=> various build cleanups

services/frontend/www-app/src/components/BaseMap.vue, services/tileserver/styles/basic/style.json
- [basemap] format
- [basemap] match water color to avoid rendering "rivers over lakes"
- [basemap] more vivid parks, grass, forest
=> more map style tweaks

services/frontend/nginx.conf.template, services/frontend/www-app/index.html
I'm proposing two separate fixes, though I'm not confident that either are a great solution.
=> Fix blank page after deploy

services/frontend/nginx.conf.template
- [www] cache font assets
- [www] cache tileserver assets
=> cache more assets

services/frontend/nginx.conf.template
I got overzealous with my prefix matching. I want the index.html to be a
fallback route only.
=> [www] fix asset caching (partial revert of 572f303)

services/travelmux/src/api/v2/plan.rs, services/travelmux/src/otp/mod.rs, services/travelmux/src/otp/otp_api.rs
=> [travelmux] FIX: draw dashed line for walking/biking trip legs

Earthfile
- **[build] fix FROM syntax for non-local container**
- **[build] slim image doesnt include curl**
=> fix gtfs download

services/frontend/www-app/src/models/Trip.ts, services/frontend/www-app/src/services/TravelmuxClient.ts
- **tweak route colors**
- **[www] FIX transit routeColor**
=> [www] tweak route colors

services/travelmux/src/api/v6/osrm_api.rs, services/travelmux/src/api/v6/plan.rs, services/travelmux/src/util/mod.rs
Useful for maplibre navigation UI
=> [travelmux] compute bearing between steps

.github/workflows/checks.yml, services/frontend/www-app/package.json, services/frontend/www-app/quasar.config.ts, services/frontend/www-app/src/layouts/MainLayout.vue, services/frontend/www-app/src/models/OpeningHours.test.ts, services/frontend/www-app/src/models/Place.ts, services/frontend/www-app/src/models/Route.ts, services/frontend/www-app/src/models/Trip.ts, services/frontend/www-app/src/router/routes.ts, services/frontend/www-app/src/ui/LocationControl.ts, services/frontend/www-app/src/ui/ScaleControl.ts, services/frontend/www-app/src/utils/decodePolyline.test.ts, services/frontend/www-app/tsconfig.json, services/frontend/www-app/yarn.lock
- **yarn upgrade --latest**
- **adapt to new quasar/vite**
=> update deps again

bin/update-deps.sh, services/frontend/www-app/src/components/SingleModeSteps.vue, services/frontend/www-app/src/services/TravelmuxClient.ts, services/frontend/www-app/src/utils/Markers.ts, services/frontend/www-app/yarn.lock, services/gtfs/gtfout/Cargo.lock, services/pelias/generate_config/yarn.lock, services/travelmux/Cargo.lock, services/travelmux/Cargo.toml, services/travelmux/src/api/v5/plan.rs, services/travelmux/src/api/v6/plan.rs, services/travelmux/src/util/mod.rs
On www, we already zoomed to the clicked maneuver, but it's helpful to have a marker on the actual map.
Getting the icon oriented correctly was just a little tricky owing to discrepancies on how our leg is chopped into maneuvers on OTP.
=> Mark selected manuever on map

Earthfile, docker-compose-with-transit.yaml, docker-compose.yaml, services/frontend/nginx.conf.template
=> expose valhalla endpoint
